# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Research/CU-Spur-Sean/spurFPGA/VivadoProjectZync/VivadoProjectZync.srcs/sources_1/bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0.xci
# IP: The module: 'design_3_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Research/CU-Spur-Sean/spurFPGA/VivadoProjectZync/VivadoProjectZync.gen/sources_1/bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Research/CU-Spur-Sean/spurFPGA/VivadoProjectZync/VivadoProjectZync.srcs/sources_1/bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0.xci
# IP: The module: 'design_3_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Research/CU-Spur-Sean/spurFPGA/VivadoProjectZync/VivadoProjectZync.gen/sources_1/bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
