
% initialize_aux1

% Function that loads the data and generates the global variables of the model.
% Inputs:
%   indRCP: RCP scenario for the CO2 emissions from non-fossil fuel combustion 
%   and the forcing from non-CO2sources; can take the value of 8.5, 6.0, 4.5 or 2.6; 
%   8.5 is the baseline.
%   maxCO2: total stock of CO2 available in the ground; 19500 is the baseline.
%   eps: elasticity of substitution between fossil fuels and clean energy;
%   1.6 is the baseline.

%% 0. Declare global variables

global H H0 amen_util0 C_vect prod0 pop0 pop0_dens pop1_dens pop5_dens u0 ...
     price_energy0 trmult_reduced n beta ...
     name_type_vect name_long_type_vect name_maps_type_vect ...
     alpha theta Omega HDI0 ...
     emi0_cell emi0 emi0_ff emi0_no_ff emi_no_ff emi_ff_data_tend chi cost_emi_param...
     a0 a1 a2 a3 b1 b2 b3 S0 S1 S2 S3 S_preind temp_preind...
     forc_sens forc_noCO2 c1 c2 d1 d2 temp1 temp2...
     temp0_global temp0_local_long temp0_local scaler_temp Delta_temp1...
     theta_amen_scen theta_prod_scen... 
     lbar lambda gamma1 gamma2 eta mu nu ksi...
     pop_low95 pop_low80 pop_med pop_high80 pop_high95...
     pop_low95_hist pop_low80_hist pop_med_hist pop_high80_hist pop_high95_hist...
     emi_ff_data forc_data length_C_vect...
     emiCO2_RCP stockCO2_RCP forc_RCP temp_global_RCP...
     price_clean0_world price_clean0 price_fossil0 zeta_clean0 zeta_fossil0 fossil_share...
     clean0_cell fossil0_cell epsilon clean_energy_data tCO2_toe map...
     color_olive color_darkgreen color_darkcyan color_yellowgreen color_greenyellow ...
     natal_param conv_usd table_prop...
     name_dam_vect name_dam_long_vect cost_CO2_data a_norm...
     natal_data country_data year_data pop_data temp_past Delta_temp max_cumCO2 natal0 natal20...

%% Print Variables in C/input
%% Load Data/derived/m2.mat and print it in C/input
