# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/zynq.xdc

# Block Designs: bd/design_3/design_3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_processing_system7_0_0/design_3_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_processing_system7_0_0 || ORIG_REF_NAME==design_3_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_loop_uhat_sparse_0_1/design_3_loop_uhat_sparse_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_loop_uhat_sparse_0_1 || ORIG_REF_NAME==design_3_loop_uhat_sparse_0_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_ps7_0_axi_periph_1/design_3_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_ps7_0_axi_periph_1 || ORIG_REF_NAME==design_3_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_rst_ps7_0_50M_1/design_3_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_rst_ps7_0_50M_1 || ORIG_REF_NAME==design_3_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xbar_0/design_3_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_xbar_0 || ORIG_REF_NAME==design_3_xbar_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_dma_0_0/design_3_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_dma_0_0 || ORIG_REF_NAME==design_3_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xbar_1/design_3_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_xbar_1 || ORIG_REF_NAME==design_3_xbar_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_mem_intercon_0/design_3_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_mem_intercon_0 || ORIG_REF_NAME==design_3_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xlconcat_0_0/design_3_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_xlconcat_0_0 || ORIG_REF_NAME==design_3_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_auto_pc_0 || ORIG_REF_NAME==design_3_auto_pc_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_auto_pc_1/design_3_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_auto_pc_1 || ORIG_REF_NAME==design_3_auto_pc_1} -quiet] -quiet

# XDC: c:/Research/CU-Spur-Sean/spurFPGA/VivadoProjectZync/VivadoProjectZync.gen/sources_1/bd/design_3/design_3_ooc.xdc
