


estim_model( coeff_pop_i, upsilon_fossil_i, upsilon_clean_i, ...
    ind_dam, update_vect, tol_vect );
toc

%% 2. Runs model backward --baseline estimation  

% Set features of the simulation
T_back = 50;            % number of periods
ind_dam = 9;            % damage function level: baseline
name_dam = name_dam_vect{ind_dam};

% Run model backwards
[ l_Warm_b, u_Warm_b, prod_Warm_b, realgdp_Warm_b, amen_Warm_b, ...
    emiCO2_ff_Warm_b, temp_local_Warm_b, ...
    price_emi_Warm_b, clean_Warm_b, ...
    price_clean_Warm_b, net_births_Warm_b ] = ...
    backward_climate( T_back, 1, ind_dam );

% Store results
save(['Data/derived/results_backward_Warm_' name_dam '.mat'],...
    'l_Warm_b', 'u_Warm_b', 'prod_Warm_b', 'realgdp_Warm_b', 'amen_Warm_b', ...
    'emiCO2_ff_Warm_b', 'temp_local_Warm_b', 'price_emi_Warm_b', ...
    'clean_Warm_b', 'price_clean_Warm_b', 'net_births_Warm_b', '-v7.3')
 
%% 3. Runs model forward --baseline estimation 

% Set features of the simulation
T = 400;                    % number of periods
ind_dam = 9;                % damage function level: baseline
% ind_dam = 1;              % damage function level: worst-scenario
name_dam = name_dam_vect{ind_dam};
taxCO2 = zeros(n,T);        % path for carbon taxes
subclean = zeros(n,T);      % path for clean energy subsidies
abat = zeros(n,T);          % path for abatement
val_adap = ones(3,1);       % degree of adaptation: baseline
         
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Model with Warming Damages
display([newline 'Warming Damages' newline])

% Run model forward
[ l_Warm, u_Warm, prod_Warm, realgdp_Warm, amen_Warm, ...
    emiCO2_ff_Warm, emiCO2_total_Warm, stockCO2_Warm, ...
    temp_global_Warm, temp_local_Warm, price_emi_Warm, ...
    clean_Warm, price_clean_Warm, net_births_Warm ] = ...
    forward_climate( T, 1, ind_dam, 0, ...
	taxCO2, subclean, abat, val_adap );

% Store results
save(['Data/derived/results_forward_Warm_' name_dam '.mat'],...
    'l_Warm', 'u_Warm', 'prod_Warm', 'realgdp_Warm', ...
    'emiCO2_ff_Warm', 'emiCO2_total_Warm', 'stockCO2_Warm', 'temp_global_Warm', ...
    'temp_local_Warm', 'amen_Warm', 'price_emi_Warm', 'clean_Warm', ...
    'price_clean_Warm', 'net_births_Warm', '-v7.3')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Model with no Warming Damages
display([newline 'No Warming Damages' newline])

% Run model forward
[ l_noWarm, u_noWarm, prod_noWarm, realgdp_noWarm, amen_noWarm, ...
    emiCO2_ff_noWarm, emiCO2_total_noWarm, stockCO2_noWarm, ...
    temp_global_noWarm, temp_local_noWarm, price_emi_noWarm, ...
    clean_noWarm, price_clean_noWarm, net_births_noWarm ] = ...
    forward_climate( T, 0, ind_dam, 0, ...
	taxCO2, subclean, abat, val_adap );

% Store results
save('Data/derived/results_forward_noWarm.mat',...
    'l_noWarm', 'u_noWarm', 'prod_noWarm', 'realgdp_noWarm', ...
    'emiCO2_ff_noWarm', 'emiCO2_total_noWarm', 'stockCO2_noWarm', 'temp_global_noWarm', ...
    'temp_local_noWarm', 'amen_noWarm', 'price_emi_noWarm', 'clean_noWarm', ...
    'price_clean_noWarm', 'net_births_noWarm', '-v7.3')

