domain_path: C:\Research\CU-Spur-Sean\spurFPGA\MatrixGainTest\VitisUnified\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
