// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="loop_uhat_sparse_loop_uhat_sparse,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=166,HLS_SYN_DSP=0,HLS_SYN_FF=19295,HLS_SYN_LUT=18391,HLS_VERSION=2023_2}" *)

module loop_uhat_sparse (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        rowStart,
        colIndex,
        value_r,
        ELEMENTS,
        tol,
        L_exp,
        R_exp,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 134'd1;
parameter    ap_ST_fsm_state2 = 134'd2;
parameter    ap_ST_fsm_state3 = 134'd4;
parameter    ap_ST_fsm_state4 = 134'd8;
parameter    ap_ST_fsm_state5 = 134'd16;
parameter    ap_ST_fsm_state6 = 134'd32;
parameter    ap_ST_fsm_state7 = 134'd64;
parameter    ap_ST_fsm_state8 = 134'd128;
parameter    ap_ST_fsm_state9 = 134'd256;
parameter    ap_ST_fsm_state10 = 134'd512;
parameter    ap_ST_fsm_state11 = 134'd1024;
parameter    ap_ST_fsm_state12 = 134'd2048;
parameter    ap_ST_fsm_state13 = 134'd4096;
parameter    ap_ST_fsm_state14 = 134'd8192;
parameter    ap_ST_fsm_state15 = 134'd16384;
parameter    ap_ST_fsm_state16 = 134'd32768;
parameter    ap_ST_fsm_state17 = 134'd65536;
parameter    ap_ST_fsm_state18 = 134'd131072;
parameter    ap_ST_fsm_state19 = 134'd262144;
parameter    ap_ST_fsm_state20 = 134'd524288;
parameter    ap_ST_fsm_state21 = 134'd1048576;
parameter    ap_ST_fsm_state22 = 134'd2097152;
parameter    ap_ST_fsm_state23 = 134'd4194304;
parameter    ap_ST_fsm_state24 = 134'd8388608;
parameter    ap_ST_fsm_state25 = 134'd16777216;
parameter    ap_ST_fsm_state26 = 134'd33554432;
parameter    ap_ST_fsm_state27 = 134'd67108864;
parameter    ap_ST_fsm_state28 = 134'd134217728;
parameter    ap_ST_fsm_state29 = 134'd268435456;
parameter    ap_ST_fsm_state30 = 134'd536870912;
parameter    ap_ST_fsm_state31 = 134'd1073741824;
parameter    ap_ST_fsm_state32 = 134'd2147483648;
parameter    ap_ST_fsm_state33 = 134'd4294967296;
parameter    ap_ST_fsm_state34 = 134'd8589934592;
parameter    ap_ST_fsm_state35 = 134'd17179869184;
parameter    ap_ST_fsm_state36 = 134'd34359738368;
parameter    ap_ST_fsm_state37 = 134'd68719476736;
parameter    ap_ST_fsm_state38 = 134'd137438953472;
parameter    ap_ST_fsm_state39 = 134'd274877906944;
parameter    ap_ST_fsm_state40 = 134'd549755813888;
parameter    ap_ST_fsm_state41 = 134'd1099511627776;
parameter    ap_ST_fsm_state42 = 134'd2199023255552;
parameter    ap_ST_fsm_state43 = 134'd4398046511104;
parameter    ap_ST_fsm_state44 = 134'd8796093022208;
parameter    ap_ST_fsm_state45 = 134'd17592186044416;
parameter    ap_ST_fsm_state46 = 134'd35184372088832;
parameter    ap_ST_fsm_state47 = 134'd70368744177664;
parameter    ap_ST_fsm_state48 = 134'd140737488355328;
parameter    ap_ST_fsm_state49 = 134'd281474976710656;
parameter    ap_ST_fsm_state50 = 134'd562949953421312;
parameter    ap_ST_fsm_state51 = 134'd1125899906842624;
parameter    ap_ST_fsm_state52 = 134'd2251799813685248;
parameter    ap_ST_fsm_state53 = 134'd4503599627370496;
parameter    ap_ST_fsm_state54 = 134'd9007199254740992;
parameter    ap_ST_fsm_state55 = 134'd18014398509481984;
parameter    ap_ST_fsm_state56 = 134'd36028797018963968;
parameter    ap_ST_fsm_state57 = 134'd72057594037927936;
parameter    ap_ST_fsm_state58 = 134'd144115188075855872;
parameter    ap_ST_fsm_state59 = 134'd288230376151711744;
parameter    ap_ST_fsm_state60 = 134'd576460752303423488;
parameter    ap_ST_fsm_state61 = 134'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 134'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 134'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 134'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 134'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 134'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 134'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 134'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 134'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 134'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 134'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 134'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 134'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 134'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 134'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 134'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 134'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 134'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 134'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 134'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 134'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 134'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 134'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 134'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 134'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 134'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 134'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 134'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 134'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 134'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 134'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 134'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 134'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 134'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 134'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 134'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 134'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 134'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 134'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 134'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 134'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 134'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 134'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 134'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 134'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 134'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 134'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 134'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 134'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 134'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 134'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 134'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 134'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 134'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 134'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 134'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 134'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 134'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 134'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 134'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 134'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 134'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 134'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 134'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 134'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 134'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 134'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 134'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 134'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 134'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state131 = 134'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state132 = 134'd2722258935367507707706996859454145691648;
parameter    ap_ST_fsm_state133 = 134'd5444517870735015415413993718908291383296;
parameter    ap_ST_fsm_state134 = 134'd10889035741470030830827987437816582766592;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 64;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input  [31:0] rowStart;
input  [31:0] colIndex;
input  [63:0] value_r;
input  [31:0] ELEMENTS;
input  [63:0] tol;
input  [63:0] L_exp;
input  [63:0] R_exp;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [133:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] L;
wire   [63:0] uhat_i;
wire   [63:0] R;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state96;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state104;
wire    ap_CS_fsm_state102;
wire    ap_CS_fsm_state110;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state111;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state112;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state117;
wire   [63:0] grp_fu_378_p2;
reg   [63:0] reg_386;
wire    ap_CS_fsm_state126;
wire    ap_CS_fsm_state8;
reg   [63:0] uhat_i_read_reg_651;
reg   [60:0] trunc_ln_reg_666;
reg   [60:0] trunc_ln31_1_reg_671;
wire  signed [61:0] sext_ln43_fu_421_p1;
reg  signed [61:0] sext_ln43_reg_676;
wire   [63:0] bitcast_ln44_fu_425_p1;
reg   [63:0] bitcast_ln44_reg_687;
reg   [14:0] integral_addr_reg_692;
wire   [0:0] or_ln27_1_fu_463_p2;
reg   [0:0] or_ln27_1_reg_697;
wire   [0:0] icmp_ln27_fu_496_p2;
reg   [0:0] icmp_ln27_reg_705;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln27_1_fu_502_p2;
reg   [0:0] icmp_ln27_1_reg_710;
wire   [63:0] integral_q0;
reg   [63:0] integral_load_reg_718;
wire    ap_CS_fsm_state14;
wire   [14:0] add_ln35_fu_529_p2;
reg   [14:0] add_ln35_reg_726;
wire    ap_CS_fsm_state15;
wire   [31:0] e_max_1_fu_545_p3;
reg   [31:0] e_max_1_reg_731;
wire   [61:0] add_ln46_fu_552_p2;
reg   [61:0] add_ln46_reg_736;
reg   [60:0] trunc_ln7_reg_741;
reg   [63:0] gmem_addr_2_reg_752;
reg   [63:0] gmem_addr_read_reg_759;
wire   [63:0] grp_pow_generic_double_s_fu_341_ap_return;
reg   [63:0] tmp_s_reg_764;
wire   [63:0] bitcast_ln46_fu_613_p1;
wire    ap_CS_fsm_state105;
reg   [63:0] gmem_addr_2_read_reg_774;
wire   [63:0] bitcast_ln47_fu_617_p1;
wire   [63:0] grp_fu_371_p2;
reg   [63:0] deviation_reg_784;
wire    ap_CS_fsm_state119;
wire    ap_CS_fsm_state134;
reg   [14:0] integral_address0;
reg    integral_ce0;
reg    integral_we0;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_start;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_done;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_idle;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_ready;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWVALID;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWADDR;
wire   [0:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWID;
wire   [31:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWLEN;
wire   [2:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWSIZE;
wire   [1:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWBURST;
wire   [1:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWLOCK;
wire   [3:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWCACHE;
wire   [2:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWPROT;
wire   [3:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWQOS;
wire   [3:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWREGION;
wire   [0:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWUSER;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WVALID;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WDATA;
wire   [7:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WSTRB;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WLAST;
wire   [0:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WID;
wire   [0:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WUSER;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARVALID;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARADDR;
wire   [0:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARID;
wire   [31:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARLEN;
wire   [2:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARSIZE;
wire   [1:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARBURST;
wire   [1:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARLOCK;
wire   [3:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARCACHE;
wire   [2:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARPROT;
wire   [3:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARQOS;
wire   [3:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARREGION;
wire   [0:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARUSER;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_RREADY;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_BREADY;
wire   [14:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_address0;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_ce0;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_we0;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_d0;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_fu_378_p_din0;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_fu_378_p_din1;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_fu_378_p_ce;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_din1;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_din2;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_ce;
wire    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_start;
wire    grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_start;
wire    grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_done;
wire    grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_idle;
wire    grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_ready;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_rhs_out;
wire    grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_rhs_out_ap_vld;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_din0;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_din1;
wire   [0:0] grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_opcode;
wire    grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_ce;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_378_p_din0;
wire   [63:0] grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_378_p_din1;
wire    grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_378_p_ce;
reg    grp_pow_generic_double_s_fu_341_ap_start;
wire    grp_pow_generic_double_s_fu_341_ap_done;
wire    grp_pow_generic_double_s_fu_341_ap_idle;
wire    grp_pow_generic_double_s_fu_341_ap_ready;
reg    grp_pow_generic_double_s_fu_341_ap_ce;
reg   [63:0] grp_pow_generic_double_s_fu_341_base_r;
reg   [63:0] grp_pow_generic_double_s_fu_341_exp;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
wire   [63:0] gmem_WDATA;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [63:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state106;
wire    ap_CS_fsm_state107;
wire    ap_CS_fsm_state108;
wire    ap_CS_fsm_state109;
wire    ap_CS_fsm_state113;
wire    ap_CS_fsm_state114;
wire    ap_CS_fsm_state115;
wire    ap_CS_fsm_state116;
wire    ap_CS_fsm_state118;
wire    ap_CS_fsm_state120;
wire    ap_CS_fsm_state121;
wire    ap_CS_fsm_state122;
wire    ap_CS_fsm_state123;
wire    ap_CS_fsm_state124;
wire    ap_CS_fsm_state125;
wire    ap_CS_fsm_state127;
wire    ap_CS_fsm_state128;
wire    ap_CS_fsm_state129;
wire    ap_CS_fsm_state130;
wire    ap_CS_fsm_state131;
wire    ap_CS_fsm_state132;
wire    ap_CS_fsm_state133;
reg   [14:0] i_1_reg_275;
reg   [63:0] error_2_reg_286;
reg    grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_start_reg;
reg    grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_start_reg;
wire   [0:0] icmp_ln35_fu_523_p2;
reg    grp_pow_generic_double_s_fu_341_ap_start_reg;
reg   [133:0] ap_NS_fsm;
wire    ap_NS_fsm_state17;
wire   [63:0] zext_ln44_fu_429_p1;
wire  signed [63:0] sext_ln46_fu_593_p1;
wire  signed [63:0] sext_ln47_fu_603_p1;
reg   [63:0] error_1_fu_158;
reg   [63:0] grp_fu_371_p0;
reg   [63:0] grp_fu_371_p1;
reg   [63:0] grp_fu_378_p0;
reg   [63:0] grp_fu_378_p1;
wire   [60:0] trunc_ln5_fu_411_p4;
wire   [63:0] bitcast_ln27_1_fu_434_p1;
wire   [10:0] tmp_4_fu_437_p4;
wire   [51:0] trunc_ln27_fu_447_p1;
wire   [0:0] icmp_ln27_3_fu_457_p2;
wire   [0:0] icmp_ln27_2_fu_451_p2;
wire   [63:0] bitcast_ln27_fu_478_p1;
wire   [10:0] tmp_3_fu_482_p4;
wire   [51:0] trunc_ln27_1_fu_492_p1;
wire   [0:0] or_ln27_fu_508_p2;
wire   [0:0] and_ln27_fu_512_p2;
wire   [0:0] grp_fu_382_p2;
wire   [0:0] icmp_ln38_fu_539_p2;
wire   [61:0] zext_ln35_fu_535_p1;
wire   [17:0] shl_ln_fu_557_p3;
wire   [63:0] zext_ln47_fu_565_p1;
wire   [63:0] add_ln47_fu_569_p2;
reg   [1:0] grp_fu_371_opcode;
reg    grp_fu_371_ce;
reg    grp_fu_378_ce;
wire   [0:0] and_ln27_1_fu_517_p2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
wire    ap_ST_fsm_state91_blk;
wire    ap_ST_fsm_state92_blk;
wire    ap_ST_fsm_state93_blk;
wire    ap_ST_fsm_state94_blk;
wire    ap_ST_fsm_state95_blk;
reg    ap_ST_fsm_state96_blk;
wire    ap_ST_fsm_state97_blk;
wire    ap_ST_fsm_state98_blk;
wire    ap_ST_fsm_state99_blk;
wire    ap_ST_fsm_state100_blk;
wire    ap_ST_fsm_state101_blk;
reg    ap_ST_fsm_state102_blk;
wire    ap_ST_fsm_state103_blk;
reg    ap_ST_fsm_state104_blk;
wire    ap_ST_fsm_state105_blk;
wire    ap_ST_fsm_state106_blk;
wire    ap_ST_fsm_state107_blk;
wire    ap_ST_fsm_state108_blk;
wire    ap_ST_fsm_state109_blk;
reg    ap_ST_fsm_state110_blk;
reg    ap_ST_fsm_state111_blk;
reg    ap_ST_fsm_state112_blk;
wire    ap_ST_fsm_state113_blk;
wire    ap_ST_fsm_state114_blk;
wire    ap_ST_fsm_state115_blk;
wire    ap_ST_fsm_state116_blk;
reg    ap_ST_fsm_state117_blk;
wire    ap_ST_fsm_state118_blk;
wire    ap_ST_fsm_state119_blk;
wire    ap_ST_fsm_state120_blk;
wire    ap_ST_fsm_state121_blk;
wire    ap_ST_fsm_state122_blk;
wire    ap_ST_fsm_state123_blk;
wire    ap_ST_fsm_state124_blk;
wire    ap_ST_fsm_state125_blk;
wire    ap_ST_fsm_state126_blk;
wire    ap_ST_fsm_state127_blk;
wire    ap_ST_fsm_state128_blk;
wire    ap_ST_fsm_state129_blk;
wire    ap_ST_fsm_state130_blk;
wire    ap_ST_fsm_state131_blk;
wire    ap_ST_fsm_state132_blk;
wire    ap_ST_fsm_state133_blk;
wire    ap_ST_fsm_state134_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 134'd1;
#0 grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_start_reg = 1'b0;
#0 grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_start_reg = 1'b0;
#0 grp_pow_generic_double_s_fu_341_ap_start_reg = 1'b0;
#0 error_1_fu_158 = 64'd0;
end

loop_uhat_sparse_integral_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 17048 ),
    .AddressWidth( 15 ))
integral_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(integral_address0),
    .ce0(integral_ce0),
    .we0(integral_we0),
    .d0(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_d0),
    .q0(integral_q0)
);

loop_uhat_sparse_loop_uhat_sparse_Pipeline_loop_uhat_integral grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_start),
    .ap_done(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_done),
    .ap_idle(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_idle),
    .ap_ready(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_ready),
    .m_axi_gmem_AWVALID(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln31(trunc_ln_reg_666),
    .sext_ln35(trunc_ln31_1_reg_671),
    .R_exp(R_exp),
    .integral_address0(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_address0),
    .integral_ce0(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_ce0),
    .integral_we0(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_we0),
    .integral_d0(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_d0),
    .grp_fu_378_p_din0(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_fu_378_p_din0),
    .grp_fu_378_p_din1(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_fu_378_p_din1),
    .grp_fu_378_p_dout0(grp_fu_378_p2),
    .grp_fu_378_p_ce(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_fu_378_p_ce),
    .grp_pow_generic_double_s_fu_341_p_din1(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_din1),
    .grp_pow_generic_double_s_fu_341_p_din2(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_din2),
    .grp_pow_generic_double_s_fu_341_p_dout0(grp_pow_generic_double_s_fu_341_ap_return),
    .grp_pow_generic_double_s_fu_341_p_ce(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_ce),
    .grp_pow_generic_double_s_fu_341_p_start(grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_start),
    .grp_pow_generic_double_s_fu_341_p_ready(grp_pow_generic_double_s_fu_341_ap_ready),
    .grp_pow_generic_double_s_fu_341_p_done(grp_pow_generic_double_s_fu_341_ap_done),
    .grp_pow_generic_double_s_fu_341_p_idle(grp_pow_generic_double_s_fu_341_ap_idle)
);

loop_uhat_sparse_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1 grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_start),
    .ap_done(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_done),
    .ap_idle(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_idle),
    .ap_ready(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_ready),
    .sext_ln43(rowStart),
    .wide_trip_count(e_max_1_reg_731),
    .bitcast_ln44(bitcast_ln44_reg_687),
    .integral_load(integral_load_reg_718),
    .rhs_out(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_rhs_out),
    .rhs_out_ap_vld(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_rhs_out_ap_vld),
    .grp_fu_371_p_din0(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_din0),
    .grp_fu_371_p_din1(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_din1),
    .grp_fu_371_p_opcode(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_opcode),
    .grp_fu_371_p_dout0(grp_fu_371_p2),
    .grp_fu_371_p_ce(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_ce),
    .grp_fu_378_p_din0(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_378_p_din0),
    .grp_fu_378_p_din1(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_378_p_din1),
    .grp_fu_378_p_dout0(grp_fu_378_p2),
    .grp_fu_378_p_ce(grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_378_p_ce)
);

loop_uhat_sparse_pow_generic_double_s grp_pow_generic_double_s_fu_341(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pow_generic_double_s_fu_341_ap_start),
    .ap_done(grp_pow_generic_double_s_fu_341_ap_done),
    .ap_idle(grp_pow_generic_double_s_fu_341_ap_idle),
    .ap_ready(grp_pow_generic_double_s_fu_341_ap_ready),
    .ap_ce(grp_pow_generic_double_s_fu_341_ap_ce),
    .base_r(grp_pow_generic_double_s_fu_341_base_r),
    .exp(grp_pow_generic_double_s_fu_341_exp),
    .ap_return(grp_pow_generic_double_s_fu_341_ap_return)
);

loop_uhat_sparse_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .L(L),
    .uhat_i(uhat_i),
    .R(R)
);

loop_uhat_sparse_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 64 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_2_reg_752),
    .I_AWLEN(32'd1),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(gmem_WDATA),
    .I_WSTRB(8'd255),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

loop_uhat_sparse_dadddsub_64ns_64ns_64_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadddsub_64ns_64ns_64_8_full_dsp_1_U60(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_371_p0),
    .din1(grp_fu_371_p1),
    .opcode(grp_fu_371_opcode),
    .ce(grp_fu_371_ce),
    .dout(grp_fu_371_p2)
);

loop_uhat_sparse_dmul_64ns_64ns_64_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_7_max_dsp_1_U61(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_378_p0),
    .din1(grp_fu_378_p1),
    .ce(grp_fu_378_ce),
    .dout(grp_fu_378_p2)
);

loop_uhat_sparse_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U62(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(error_1_fu_158),
    .din1(tol),
    .ce(1'b1),
    .opcode(5'd3),
    .dout(grp_fu_382_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln35_fu_523_p2 == 1'd0))) begin
            grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_start_reg <= 1'b1;
        end else if ((grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_ready == 1'b1)) begin
            grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_start_reg <= 1'b1;
        end else if ((grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_ready == 1'b1)) begin
            grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pow_generic_double_s_fu_341_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state17) & (1'b1 == ap_CS_fsm_state16))) begin
            grp_pow_generic_double_s_fu_341_ap_start_reg <= 1'b1;
        end else if ((grp_pow_generic_double_s_fu_341_ap_ready == 1'b1)) begin
            grp_pow_generic_double_s_fu_341_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        error_1_fu_158 <= grp_fu_371_p2;
    end else if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln35_fu_523_p2 == 1'd1))) begin
        error_1_fu_158 <= error_2_reg_286;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state134)) begin
        error_2_reg_286 <= grp_fu_371_p2;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        error_2_reg_286 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state134)) begin
        i_1_reg_275 <= add_ln35_reg_726;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        i_1_reg_275 <= 15'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln35_reg_726 <= add_ln35_fu_529_p2;
        add_ln46_reg_736 <= add_ln46_fu_552_p2;
        e_max_1_reg_731 <= e_max_1_fu_545_p3;
        trunc_ln7_reg_741 <= {{add_ln47_fu_569_p2[63:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        bitcast_ln44_reg_687 <= bitcast_ln44_fu_425_p1;
        integral_addr_reg_692 <= zext_ln44_fu_429_p1;
        or_ln27_1_reg_697 <= or_ln27_1_fu_463_p2;
        sext_ln43_reg_676 <= sext_ln43_fu_421_p1;
        trunc_ln31_1_reg_671 <= {{uhat_i[63:3]}};
        trunc_ln_reg_666 <= {{R[63:3]}};
        uhat_i_read_reg_651 <= uhat_i;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state119)) begin
        deviation_reg_784 <= grp_fu_371_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state110)) begin
        gmem_addr_2_read_reg_774 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state102)) begin
        gmem_addr_2_reg_752 <= sext_ln47_fu_603_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state104)) begin
        gmem_addr_read_reg_759 <= gmem_RDATA;
        tmp_s_reg_764 <= grp_pow_generic_double_s_fu_341_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln27_1_reg_710 <= icmp_ln27_1_fu_502_p2;
        icmp_ln27_reg_705 <= icmp_ln27_fu_496_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        integral_load_reg_718 <= integral_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state126) | (1'b1 == ap_CS_fsm_state111))) begin
        reg_386 <= grp_fu_378_p2;
    end
end

assign ap_ST_fsm_state100_blk = 1'b0;

assign ap_ST_fsm_state101_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state102_blk = 1'b1;
    end else begin
        ap_ST_fsm_state102_blk = 1'b0;
    end
end

assign ap_ST_fsm_state103_blk = 1'b0;

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state104_blk = 1'b1;
    end else begin
        ap_ST_fsm_state104_blk = 1'b0;
    end
end

assign ap_ST_fsm_state105_blk = 1'b0;

assign ap_ST_fsm_state106_blk = 1'b0;

assign ap_ST_fsm_state107_blk = 1'b0;

assign ap_ST_fsm_state108_blk = 1'b0;

assign ap_ST_fsm_state109_blk = 1'b0;

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state110_blk = 1'b1;
    end else begin
        ap_ST_fsm_state110_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_AWREADY == 1'b0)) begin
        ap_ST_fsm_state111_blk = 1'b1;
    end else begin
        ap_ST_fsm_state111_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_WREADY == 1'b0)) begin
        ap_ST_fsm_state112_blk = 1'b1;
    end else begin
        ap_ST_fsm_state112_blk = 1'b0;
    end
end

assign ap_ST_fsm_state113_blk = 1'b0;

assign ap_ST_fsm_state114_blk = 1'b0;

assign ap_ST_fsm_state115_blk = 1'b0;

assign ap_ST_fsm_state116_blk = 1'b0;

always @ (*) begin
    if ((gmem_BVALID == 1'b0)) begin
        ap_ST_fsm_state117_blk = 1'b1;
    end else begin
        ap_ST_fsm_state117_blk = 1'b0;
    end
end

assign ap_ST_fsm_state118_blk = 1'b0;

assign ap_ST_fsm_state119_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state120_blk = 1'b0;

assign ap_ST_fsm_state121_blk = 1'b0;

assign ap_ST_fsm_state122_blk = 1'b0;

assign ap_ST_fsm_state123_blk = 1'b0;

assign ap_ST_fsm_state124_blk = 1'b0;

assign ap_ST_fsm_state125_blk = 1'b0;

assign ap_ST_fsm_state126_blk = 1'b0;

assign ap_ST_fsm_state127_blk = 1'b0;

assign ap_ST_fsm_state128_blk = 1'b0;

assign ap_ST_fsm_state129_blk = 1'b0;

always @ (*) begin
    if ((grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state130_blk = 1'b0;

assign ap_ST_fsm_state131_blk = 1'b0;

assign ap_ST_fsm_state132_blk = 1'b0;

assign ap_ST_fsm_state133_blk = 1'b0;

assign ap_ST_fsm_state134_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

assign ap_ST_fsm_state91_blk = 1'b0;

assign ap_ST_fsm_state92_blk = 1'b0;

assign ap_ST_fsm_state93_blk = 1'b0;

assign ap_ST_fsm_state94_blk = 1'b0;

assign ap_ST_fsm_state95_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state96_blk = 1'b1;
    end else begin
        ap_ST_fsm_state96_blk = 1'b0;
    end
end

assign ap_ST_fsm_state97_blk = 1'b0;

assign ap_ST_fsm_state98_blk = 1'b0;

assign ap_ST_fsm_state99_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (1'd0 == and_ln27_1_fu_517_p2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (1'd0 == and_ln27_1_fu_517_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state102))) begin
        gmem_ARADDR = sext_ln47_fu_603_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state96))) begin
        gmem_ARADDR = sext_ln46_fu_593_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_ARADDR = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state102)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state96)))) begin
        gmem_ARLEN = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_ARLEN = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state102)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state96)))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_ARVALID = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state111))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state117))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state110)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state104)))) begin
        gmem_RREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_RREADY = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state112))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state102) | (1'b1 == ap_CS_fsm_state96))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state111)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state117)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state110) | (1'b1 == ap_CS_fsm_state104))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state112)) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_371_ce = grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state134) | (1'b1 == ap_CS_fsm_state119) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state133) | (1'b1 == ap_CS_fsm_state132) | (1'b1 == ap_CS_fsm_state131) | (1'b1 == ap_CS_fsm_state130) | (1'b1 == ap_CS_fsm_state129) | (1'b1 == ap_CS_fsm_state128) | (1'b1 == ap_CS_fsm_state127) | (1'b1 == ap_CS_fsm_state118) | (1'b1 == ap_CS_fsm_state116) | (1'b1 == ap_CS_fsm_state115) | (1'b1 == ap_CS_fsm_state114) | (1'b1 == ap_CS_fsm_state113) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state112)) | ((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state117)))) begin
        grp_fu_371_ce = 1'b1;
    end else begin
        grp_fu_371_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_371_opcode = grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state112)) begin
        grp_fu_371_opcode = 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state127) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        grp_fu_371_opcode = 2'd0;
    end else begin
        grp_fu_371_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_371_p0 = grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        grp_fu_371_p0 = error_2_reg_286;
    end else if ((1'b1 == ap_CS_fsm_state112)) begin
        grp_fu_371_p0 = bitcast_ln47_fu_617_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_371_p0 = tol;
    end else begin
        grp_fu_371_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_371_p1 = grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_371_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state112) | (1'b1 == ap_CS_fsm_state127))) begin
        grp_fu_371_p1 = reg_386;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_371_p1 = 64'd4607182418800017408;
    end else begin
        grp_fu_371_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_378_ce = grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_378_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_378_ce = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_fu_378_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state105) | (1'b1 == ap_CS_fsm_state126) | (1'b1 == ap_CS_fsm_state125) | (1'b1 == ap_CS_fsm_state124) | (1'b1 == ap_CS_fsm_state123) | (1'b1 == ap_CS_fsm_state122) | (1'b1 == ap_CS_fsm_state121) | (1'b1 == ap_CS_fsm_state120) | (1'b1 == ap_CS_fsm_state109) | (1'b1 == ap_CS_fsm_state108) | (1'b1 == ap_CS_fsm_state107) | (1'b1 == ap_CS_fsm_state106) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state110)) | ((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state111)))) begin
        grp_fu_378_ce = 1'b1;
    end else begin
        grp_fu_378_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_378_p0 = grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_378_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_378_p0 = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_fu_378_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state120)) begin
        grp_fu_378_p0 = deviation_reg_784;
    end else if ((1'b1 == ap_CS_fsm_state105)) begin
        grp_fu_378_p0 = bitcast_ln46_fu_613_p1;
    end else begin
        grp_fu_378_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_378_p1 = grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_grp_fu_378_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_378_p1 = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_fu_378_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state120)) begin
        grp_fu_378_p1 = deviation_reg_784;
    end else if ((1'b1 == ap_CS_fsm_state105)) begin
        grp_fu_378_p1 = tmp_s_reg_764;
    end else begin
        grp_fu_378_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_pow_generic_double_s_fu_341_ap_ce = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state134) | (1'b1 == ap_CS_fsm_state119) | (1'b1 == ap_CS_fsm_state105) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state126) | (1'b1 == ap_CS_fsm_state117) | (1'b1 == ap_CS_fsm_state112) | (1'b1 == ap_CS_fsm_state111) | (1'b1 == ap_CS_fsm_state110) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state133) | (1'b1 == ap_CS_fsm_state132) | (1'b1 == ap_CS_fsm_state131) | (1'b1 == ap_CS_fsm_state130) | (1'b1 == ap_CS_fsm_state129) | (1'b1 == ap_CS_fsm_state128) | (1'b1 == ap_CS_fsm_state127) | (1'b1 == ap_CS_fsm_state125) | (1'b1 == ap_CS_fsm_state124) | (1'b1 == ap_CS_fsm_state123) | (1'b1 == ap_CS_fsm_state122) | (1'b1 == ap_CS_fsm_state121) | (1'b1 == ap_CS_fsm_state120) 
    | (1'b1 == ap_CS_fsm_state118) | (1'b1 == ap_CS_fsm_state116) | (1'b1 == ap_CS_fsm_state115) | (1'b1 == ap_CS_fsm_state114) | (1'b1 == ap_CS_fsm_state113) | (1'b1 == ap_CS_fsm_state109) | (1'b1 == ap_CS_fsm_state108) | (1'b1 == ap_CS_fsm_state107) | (1'b1 == ap_CS_fsm_state106) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | ((gmem_RVALID == 1'b0) & (1'b1 == ap_CS_fsm_state104)) | ((gmem_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state102)) | ((gmem_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state96)))) begin
        grp_pow_generic_double_s_fu_341_ap_ce = 1'b0;
    end else begin
        grp_pow_generic_double_s_fu_341_ap_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_pow_generic_double_s_fu_341_ap_start = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_start;
    end else begin
        grp_pow_generic_double_s_fu_341_ap_start = grp_pow_generic_double_s_fu_341_ap_start_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_pow_generic_double_s_fu_341_base_r = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_pow_generic_double_s_fu_341_base_r = grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_rhs_out;
    end else begin
        grp_pow_generic_double_s_fu_341_base_r = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_pow_generic_double_s_fu_341_exp = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_grp_pow_generic_double_s_fu_341_p_din2;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_pow_generic_double_s_fu_341_exp = L_exp;
    end else begin
        grp_pow_generic_double_s_fu_341_exp = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        integral_address0 = integral_addr_reg_692;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        integral_address0 = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_address0;
    end else begin
        integral_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        integral_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        integral_ce0 = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_ce0;
    end else begin
        integral_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        integral_we0 = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_integral_we0;
    end else begin
        integral_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (1'd0 == and_ln27_1_fu_517_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln35_fu_523_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state96))) begin
                ap_NS_fsm = ap_ST_fsm_state97;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state96;
            end
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state102))) begin
                ap_NS_fsm = ap_ST_fsm_state103;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state102;
            end
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state104))) begin
                ap_NS_fsm = ap_ST_fsm_state105;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state104;
            end
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state110))) begin
                ap_NS_fsm = ap_ST_fsm_state111;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state110;
            end
        end
        ap_ST_fsm_state111 : begin
            if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state111))) begin
                ap_NS_fsm = ap_ST_fsm_state112;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state111;
            end
        end
        ap_ST_fsm_state112 : begin
            if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state112))) begin
                ap_NS_fsm = ap_ST_fsm_state113;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state112;
            end
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state117))) begin
                ap_NS_fsm = ap_ST_fsm_state118;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state117;
            end
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state133;
        end
        ap_ST_fsm_state133 : begin
            ap_NS_fsm = ap_ST_fsm_state134;
        end
        ap_ST_fsm_state134 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln35_fu_529_p2 = (i_1_reg_275 + 15'd1);

assign add_ln46_fu_552_p2 = ($signed(zext_ln35_fu_535_p1) + $signed(sext_ln43_reg_676));

assign add_ln47_fu_569_p2 = (zext_ln47_fu_565_p1 + uhat_i_read_reg_651);

assign and_ln27_1_fu_517_p2 = (grp_fu_382_p2 & and_ln27_fu_512_p2);

assign and_ln27_fu_512_p2 = (or_ln27_fu_508_p2 & or_ln27_1_reg_697);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state102 = ap_CS_fsm[32'd101];

assign ap_CS_fsm_state104 = ap_CS_fsm[32'd103];

assign ap_CS_fsm_state105 = ap_CS_fsm[32'd104];

assign ap_CS_fsm_state106 = ap_CS_fsm[32'd105];

assign ap_CS_fsm_state107 = ap_CS_fsm[32'd106];

assign ap_CS_fsm_state108 = ap_CS_fsm[32'd107];

assign ap_CS_fsm_state109 = ap_CS_fsm[32'd108];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state110 = ap_CS_fsm[32'd109];

assign ap_CS_fsm_state111 = ap_CS_fsm[32'd110];

assign ap_CS_fsm_state112 = ap_CS_fsm[32'd111];

assign ap_CS_fsm_state113 = ap_CS_fsm[32'd112];

assign ap_CS_fsm_state114 = ap_CS_fsm[32'd113];

assign ap_CS_fsm_state115 = ap_CS_fsm[32'd114];

assign ap_CS_fsm_state116 = ap_CS_fsm[32'd115];

assign ap_CS_fsm_state117 = ap_CS_fsm[32'd116];

assign ap_CS_fsm_state118 = ap_CS_fsm[32'd117];

assign ap_CS_fsm_state119 = ap_CS_fsm[32'd118];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state120 = ap_CS_fsm[32'd119];

assign ap_CS_fsm_state121 = ap_CS_fsm[32'd120];

assign ap_CS_fsm_state122 = ap_CS_fsm[32'd121];

assign ap_CS_fsm_state123 = ap_CS_fsm[32'd122];

assign ap_CS_fsm_state124 = ap_CS_fsm[32'd123];

assign ap_CS_fsm_state125 = ap_CS_fsm[32'd124];

assign ap_CS_fsm_state126 = ap_CS_fsm[32'd125];

assign ap_CS_fsm_state127 = ap_CS_fsm[32'd126];

assign ap_CS_fsm_state128 = ap_CS_fsm[32'd127];

assign ap_CS_fsm_state129 = ap_CS_fsm[32'd128];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state130 = ap_CS_fsm[32'd129];

assign ap_CS_fsm_state131 = ap_CS_fsm[32'd130];

assign ap_CS_fsm_state132 = ap_CS_fsm[32'd131];

assign ap_CS_fsm_state133 = ap_CS_fsm[32'd132];

assign ap_CS_fsm_state134 = ap_CS_fsm[32'd133];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state96 = ap_CS_fsm[32'd95];

assign ap_NS_fsm_state17 = ap_NS_fsm[32'd16];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln27_1_fu_434_p1 = tol;

assign bitcast_ln27_fu_478_p1 = error_1_fu_158;

assign bitcast_ln44_fu_425_p1 = value_r;

assign bitcast_ln46_fu_613_p1 = gmem_addr_read_reg_759;

assign bitcast_ln47_fu_617_p1 = gmem_addr_2_read_reg_774;

assign e_max_1_fu_545_p3 = ((icmp_ln38_fu_539_p2[0:0] == 1'b1) ? rowStart : ELEMENTS);

assign gmem_WDATA = reg_386;

assign grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_start = grp_loop_uhat_sparse_Pipeline_VITIS_LOOP_43_1_fu_332_ap_start_reg;

assign grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_start = grp_loop_uhat_sparse_Pipeline_loop_uhat_integral_fu_298_ap_start_reg;

assign icmp_ln27_1_fu_502_p2 = ((trunc_ln27_1_fu_492_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln27_2_fu_451_p2 = ((tmp_4_fu_437_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln27_3_fu_457_p2 = ((trunc_ln27_fu_447_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_496_p2 = ((tmp_3_fu_482_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_523_p2 = ((i_1_reg_275 == 15'd17048) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_539_p2 = ((i_1_reg_275 < 15'd17047) ? 1'b1 : 1'b0);

assign or_ln27_1_fu_463_p2 = (icmp_ln27_3_fu_457_p2 | icmp_ln27_2_fu_451_p2);

assign or_ln27_fu_508_p2 = (icmp_ln27_reg_705 | icmp_ln27_1_reg_710);

assign sext_ln43_fu_421_p1 = $signed(trunc_ln5_fu_411_p4);

assign sext_ln46_fu_593_p1 = $signed(add_ln46_reg_736);

assign sext_ln47_fu_603_p1 = $signed(trunc_ln7_reg_741);

assign shl_ln_fu_557_p3 = {{i_1_reg_275}, {3'd0}};

assign tmp_3_fu_482_p4 = {{bitcast_ln27_fu_478_p1[62:52]}};

assign tmp_4_fu_437_p4 = {{bitcast_ln27_1_fu_434_p1[62:52]}};

assign trunc_ln27_1_fu_492_p1 = bitcast_ln27_fu_478_p1[51:0];

assign trunc_ln27_fu_447_p1 = bitcast_ln27_1_fu_434_p1[51:0];

assign trunc_ln5_fu_411_p4 = {{L[63:3]}};

assign zext_ln35_fu_535_p1 = i_1_reg_275;

assign zext_ln44_fu_429_p1 = colIndex;

assign zext_ln47_fu_565_p1 = shl_ln_fu_557_p3;

endmodule //loop_uhat_sparse
